runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static
  expiration: 7d

- url: /
  script: _go_app

- url: /login
  script: _go_app

- url: /bipedaler/(.*)
  script: _go_app

- url: /blog
  script: _go_app

- url: /blog(.*)
  script: _go_app

- url: /media
  script: _go_app

- url: /media(.*)
  script: _go_app
